<<<<<<< HEAD
sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g gulp-cli

script: gulp test:ci

after_success: gulp coveralls

cache:
  yarn: true
  
=======
language: node_js
sudo: false
node_js:
- '6.10.0'
>>>>>>> e85096014005bb17ae713b348d68a3b672d7fb85
